### ISSUE TITLE
Memory error when use use_me.py

### ISSUE THREAD

**Issue by djpg** [dr-costas/mad-twinnet#1] opened 2018-02-23 11:23 UTC
Hi, I have trained with my own data and when I'm going to use the use_me.py script I get the following error:

```python
Traceback (most recent call last):
  File "scripts/use_me.py", line 200, in <module>
    main()
  File "scripts/use_me.py", line 195, in main
    output_file_names=_make_target_file_names(input_list)
  File "scripts/use_me.py", line 113, in use_me_process
    output_file_name=output_file_names[index]
  File "/home/david/ASR/mad-twinnet/helpers/data_feeder.py", line 191, in data_process_results_testing
    bg_hat = mix[:min_len] - voice_hat[:min_len]
MemoryError
```
Anyone knows what's the problem?

PD: Excellent project! It's amazing.

**Comment by dr-costas** [comment] 2018-02-23 11:49
Hey!

Thank you very much for reporting this. 

Could you repeat the process but without GPU so PyTorch will give a more informative message? Or is it already in CPU?

**Comment by dr-costas** [comment] 2018-02-23 11:56
I just used myself the `use_me` script and searched a bit for your problem. 

It might be problem with the size of your data. Could you have a look at: 

https://stackoverflow.com/questions/5537618/memory-errors-and-list-limits

And let me know if you found something that can help you with this problem? 

Also, I could suggest using a breakpoint at the line 191 of helpers/data_feeder.py and see the size of the arrays there.

**Comment by ghost** [comment] 2018-02-24 17:56
I have the same issue, I even used the same mix.wav file from your website as input and it doesn't work. Is there a way to check if torch within python is running on cpu or gpu? I am assuming you trained the weights on GPU, however do I also need a gpu to test the script or can I use the cpu alone. I have 8GB of RAM, is that the reason? 

However, memory problems shouldn't be a problem anyway, especially in the testing/prediction phase. Most neural networks in python don't have this memory issue at the prediction stage, they only require memory in the training stage. So this is, in some way, a problem with your code. In the meantime, I will try to solve this problem in some way. 

Thanks a lot for your hard work on this project! 

p.s.: i used ALL the default settings and didn't train anything myself, only used pre-trained weights from Zenodo and mix.wav from your website.

**Comment by ghost** [comment] 2018-02-24 19:38
I solved the issue. I was thinking about stereo files and I said to myself, what if the input is a stereo wav instead of mono wav and it works! Now the only thing to figure out here is how to make this work nicely by exporting to stereo instead of 2 mono files (voice and background music).

**Comment by djpg** [comment] 2018-02-26 07:19
I'm running over GPU and with mono audio files. The sizes are:  
```python
print(len(mix[:min_len]))
380007
print(len(voice_hat[:min_len]))
380007
```
I don't know if the problem is with mono files as @dankorg said.

**Comment by dr-costas** [comment] 2018-02-26 21:27
Hi! 

Thank you all for your time reporting this. I will have a look tomorrow, focusing on what you guys said. 

I will let you know the soonest as I fix this issue.

**Comment by dr-costas** [comment] 2018-02-28 14:05
Hi!

I think now the issue is fixed. You can pull the updated code.

**Comment by djpg** [comment] 2018-03-01 08:47
Hi!

Now it's working for me. I'm going to make some testing and close the issue then.

Thank you!

**Comment by dr-costas** [comment] 2018-03-07 11:18
@djpg 

Is everything OK? Shall I close this issue?

**Comment by djpg** [comment] 2018-03-07 12:51
@dr-costas 

Now when I'm training with mono audio files 8KHz and change it on helpers/settings.py ``wav_quality = {'sampling_rate': 8000, 'nb_bits': 8}``

```bash
Traceback (most recent call last):
  File "scripts/training.py", line 199, in <module>
    main()
  File "scripts/training.py", line 195, in main
    training_process()
  File "scripts/training.py", line 176, in training_process
    l_m=torch.mean(torch.FloatTensor(epoch_l_m)),
RuntimeError: invalid argument 1: empty Tensor at /pytorch/torch/lib/TH/generic/THTensorMath.c:3381

```

Thank you!

**Comment by dr-costas** [comment] 2018-03-07 12:56
OK! I will check this. 

Since it is a different problem, I will transfer it to a new issue.

**Comment by dr-costas** [comment] 2018-03-07 13:00
Since this memory issue is fixed, I close this issue. 

Please feel free to post here if the same issue is encountered.

**Closed as completed by dr-costas** 2018-03-07 13:00 UTC

**Comment by dr-costas** [comment] 2018-03-07 14:00
@djpg 

It seems that I cannot reproduce this error. I just tried to train the system with 8bits files and it works just fine. 

The error says that in an epoch you had no loss value from the masker and thus the list that accumulates the losses from each iteration (`epoch_l_m`) is empty. 

Could you please check your settings? Also, let me know the status of this issue at the new issue that I made. 

Thank you agani for your time in this. 

Cheers!
